### PR TITLE
Update StanfordTextEditorTest

### PR DESCRIPTION
**Pull request by joegl**
# READY FOR REVIEW

# Summary
- Fixes two test errors with the `StanfordTextEditorTest`
1. The `file.usage` service was added to `stanford_media` so the `file` module needs to be included in the test.
2. Misalignment of Link/DrupalLink between the `stanford_minimal_html` configuration and the test. I'm not sure why this didn't throw errors until now; both the test and configuration have been unaltered for months. https://github.com/SU-SWS/stanford_profile/blob/text-editor-test-fix/modules/stanford_text_editor/tests/src/Kernel/StanfordTextEditorTest.php#L78

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Urgency
- How urgent is this? (Normal, High)

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Navigate to...
4. Verify...

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory?

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by joegl** [comment]
@pookmish I have no idea why the PHP Unit test keeps failing on asserting the `drupallink` key exists for the minimal_html text format. I've debugged locally and the key is there, along with the rest of the values the test checks. I also setup PHPUnit locally and ran the test by itself without issue:

```
Testing Drupal\Tests\stanford_text_editor\Kernel\StanfordTextEditorTest
..                                                                  2 / 2 (100%)

Time: 00:01.585, Memory: 10.00 MB

OK (2 tests, 37 assertions)
```

**Comment by joegl** [comment]
> @pookmish I have no idea why the PHP Unit test keeps failing on asserting the `drupallink` key exists for the minimal_html text format. I've debugged locally and the key is there, along with the rest of the values the test checks. I also setup PHPUnit locally and ran the test by itself without issue:
> 
> ```
> Testing Drupal\Tests\stanford_text_editor\Kernel\StanfordTextEditorTest
> ..                                                                  2 / 2 (100%)
> 
> Time: 00:01.585, Memory: 10.00 MB
> 
> OK (2 tests, 37 assertions)
> ```

I also ran the whole profile test locally and it all checked out (although there were some deprecation notices).

**Comment by joegl** [comment]
This is the line that keeps failing: https://github.com/SU-SWS/stanford_profile/blob/text-editor-test-fix/modules/stanford_text_editor/tests/src/Kernel/StanfordTextEditorTest.php#L78

**Review by pookmish — APPROVED** [review]
Wonder how it always worked previously

**Pull request merged**
