### PR TITLE
D8CORE-6336: changing hover on print icon for policy CT

### PR DESCRIPTION
**Pull request by jenbreese**
# READY FOR REVIEW

# Summary
- Changed the hover, active and focus state for the print icon/link on the Policy content type

# Review By (Date)
- 5/15

# Criticality
- Normal

# Urgency
- Normal

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Navigate to a policy page.
4. Verify the print link and icon have no underline and then on active/hover/focus there is an underline and color change.

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory? NO

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
[- D8CORE-6336](https://stanfordits.atlassian.net/browse/D8CORE-6336)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by pookmish** [comment]
@jenbreese & @jdwjdwjdw, for the next few weeks, any work has to be merged into 10.x & 9.x branches. So if you can please notify me when the work is good to go, i'll get it into both versions

**Comment by jenbreese** [comment]
@pookmish and @jdwjdwjdw Ok, great.  Thank you.  I have a codeclimate issue to fix.  Because this PR goes into the 10.x branch, do I need to merge the 10.x branch into my `bug/D8CORE-6336--print-link`?

**Comment by pookmish** [comment]
I already updated this PR for the 10.x. You'll want to update your local `git fetch && git reset --hard origin bug/D8CORE-6336--print-link`

**Comment by jenbreese** [comment]
I got an error: `fatal: Cannot do hard reset with paths` Is it because I used the `bug/` in the path name?

**Review by jdwjdwjdw — APPROVED** [review]
Changes are looking good to me 👍

**Comment by jenbreese** [comment]
Hi @pookmish @jdwjdwjdw approved this pr.  You said to let you know when it is approved so it can be put into both` 9.x` and `10.x`?

**Review by pookmish — APPROVED** [review]

**Pull request merged**
