### PR TITLE
Changed default workgroup for saml role mapping

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Changed workgroups to limit who has access

# Need Review By (Date)
- next release

# Urgency
- medium

# Steps to Test
1. Checkout this branch
1. do a fresh install
1. log into your local site
1. verify you still have admin.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
Wait for green lights.

**Comment by jbickar** [comment]
Is this needed also? https://github.com/SU-SWS/stanford_ssp/pull/86

**Comment by pookmish** [comment]
Wouldn't hurt to have the help text changed too.

**Comment by pookmish** [comment]
green light

**Pull request merged**
