### PR TITLE
D8CORE-938: Menu tweaks.

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW 

# Summary
- Update Webpack builds
- Hide secondary nav at everything less than and equal to the `md` breakpoint on stanford page
- Set branches for dependant work to D8CORE-938
- Update Decanter to 6.0.1

# Review By (Date)
- End of the week

# Urgency
- Medium

# Steps to Test

1. Review code
2. Use the tugboat build at: https://github.com/SU-SWS/acsf-cardinalsites/pull/46 or https://navigation-test.sites.stanford.edu/ to review the hide/show functionality of the navigation split.
3. Test the webpack compile by running `npm run publish` to ensure no further changes.

# Affected Projects or Products
- D8CORE

# Associated Issues and/or People
- D8CORE-901 
- D8CORE-938
- @katrialesser FYI
- @pookmish FYI

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
Kerri has already reviewed the navigation for aesthetics so don't worry about that but I still need a review on:

Code and approach: @boznik 
Accessibility fixes: @cjwest 

Thanks,

**Comment by cjwest** [comment]
I'm still figuring out how best to do the testing with AMP. I just created a new asset:
https://stanford.levelaccess.net/public/reporting/view_system.php?system_id=36325

No nav issues reported by AMP

**Comment by sherakama** [comment]
Just the navigation is all that should be required from level access at this point.

**Comment by sherakama** [comment]
Level access report on the Navigation: https://stanford.levelaccess.net/public/reporting/view_report.php?report_id=285013 

Two issues that will be resolved in another PR.

**Pull request merged**
