### PR TITLE
Exported configs after D9.1 database updates

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Due to the theme dependency changes, we need to move to exclusively D9 with this.
- Ran an install with the latest D8, install D9, did a database update and config export.
- Updated version of modules for D9.
- Do config overrides to manipulate the config_ignore settings when doing a site install. We need this because the system.theme configs would be ignored during install.

# Need Review By (Date)
- 1/15/2021

# Urgency
- medium

# Steps to Test
1. follow steps in https://github.com/SU-SWS/acsf-cardinalsites/pull/212

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Review by sherakama — CHANGES_REQUESTED** [review]
Changes look legit. Passing tests is your merge blocker.

**Comment by sherakama** [comment]
Ok, @imonroe please have a pass at this before merge.

**Review by imonroe — APPROVED** [review]
Looks good.  What's up with CodeClimate on this?  Looks like it just hung?

**Comment by pookmish** [comment]
Codeclimate will only scan when the merge is going into the "Default" branch. right now the default branch is set to `8.x-1.x`. So just before I merge this i'll switch default branches and trigger Codeclimate.

**Comment by sherakama** [comment]
> Codeclimate will only scan when the merge is going into the "Default" branch. right now the default branch is set to `8.x-1.x`. So just before I merge this i'll switch default branches and trigger Codeclimate.

This bugs me very much about code climate. If anyone has some time perhaps look into https://www.codacy.com/ as an alternative. I am not married to codeclimate. It is ok but could be better.

**Pull request merged**
