### PR TITLE
 Updated default content module

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Updated default content module.

# Need Review By (Date)
- 12/3

# Urgency
- low

# Steps to Test
1. `composer require su-sws/stanford_profile:dev-D8CORE-000-default-content --no-update`
1. `composer update -n`
1. `blt di -n`
1. validate the default content exists on the site.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by imonroe** [comment]
Following the instructions above, I get:

image

**Comment by pookmish** [comment]
Try deleting the `default_content` directory and try again. It's trying to apply a patch that should no longer exist in any composer.json file.

**Comment by imonroe** [comment]
The patch is still called for in the composer.json: 
https://github.com/SU-SWS/stanford_profile/blob/3d677f1d7eda195ece2d9c44a562c70143207fec/composer.json#L168

Composer won't finish the installation.

**Comment by pookmish** [comment]
There are 4 places that patch exists in composer.json's. `stanford_profile`, `stanford_events`, `stanford_news`, and `stanford_person`. All of which are modified in this pr. Your composer is attempting to apply an old patch that should no longer be configured. Try deleting your `vendor` directory and `docroot/modules/contrib/*` and try the `composer update` again

**Review by imonroe — APPROVED** [review]
This works for me now.  Default content appears correct.  I'll green-light this, but not merge it, since it relies on branches in the other repos getting merged.

**Pull request merged**
