### PR TITLE
Added field_formatter_class module

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- What the title sayz

# Need Review By (Date)
- :man_shrugging: 

# Urgency
- low

# Steps to Test
1. validate the module is added.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
Have you tested it out?
Re: https://www.drupal.org/project/field_formatter_class/issues/3046372

Also, what is requiring this?

**Comment by pookmish** [comment]
Hmm. i wonder how i did that in H&S.

@jenbreese was asking how to add a class to the page title when in a full width display. figured this could be an easy solution to add a class in the layout library.

**Comment by jenbreese** [comment]
I wanted to manipulate the margin left on the titles for this Jira. https://stanfordits.atlassian.net/browse/D8CORE-1019 The way the css is means I can't add the margin for a full width without adding to the other view. I can show you tomorrow.

**Comment by sherakama** [comment]
I think it is a good module to add. Please validate that it works and that all required patches are applied.

**Comment by pookmish** [comment]
Patched the module. i'll add to a branch of `acsf-cardinalsites`

**Comment by pookmish** [comment]
https://github.com/SU-SWS/acsf-cardinalsites/pull/74

**Pull request merged**
