### PR TITLE
D8CORE-2685 Enable react behaviors module

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Enable the react_paragraphs_behaviors module

# Need Review By (Date)
- after https://github.com/SU-SWS/react_paragraphs/pull/70 is merged

# Urgency
- low

# Steps to Test

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by pookmish** [comment]
@sherakama good with this after the react_paragraphs is merged?

**Comment by sherakama** [comment]
> @sherakama good with this after the react_paragraphs is merged?

Do you want to wait until after the freeze or no?

**Comment by pookmish** [comment]
Doesn't matter much to me. its a small amount in here so i'm good with it going out before the freeze.

**Comment by pookmish** [comment]
Merged, if you feel like we need to pull it, its an easy task.

**Pull request merged**
