### PR TITLE
Added notifications about events and person importer

### PR DESCRIPTION
**Pull request by pookmish**
# Ready for Review

### CODE REVIEW

**Comment by sherakama** [comment]
@pookmish ready to go?

**Comment by pookmish** [comment]
oh yeah. did you wanna add notification for the buttons?

**Comment by sherakama** [comment]
I do, @cjwest what is the URL for the button alignment documentation?

**Comment by cjwest** [comment]
@sherakama,

The documentation for button alignment is at:
https://userguide.sites.stanford.edu/tour/paragraphs/text-area/working-with-buttons

This is unpublished at the moment pending update for the new approach.

cc @jdwjdwjdw

**Comment by sherakama** [comment]
Thanks @cjwest

**Pull request merged**
