### PR TITLE
Removed unnecessary field permission third party settings

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Removed field permission third party settings
- see https://github.com/SU-SWS/stanford_profile_helper/pull/26

# Need Review By (Date)
- :man_shrugging: 

# Urgency
- low

# Steps to Test
1. checkout this branch.
1. do an install or config import
1. see that it still works like normal.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
Won't these just keep coming back? I know we don't need them but won't exports become troublesome?

**Comment by sherakama** [comment]
Oh I see https://github.com/SU-SWS/stanford_profile_helper/pull/26 now.

**Comment by sherakama** [comment]
I don't really mind having these field_permissions in this profile repo but I do agree it creates a mess in our modules. The default setting is public so I think this is ok, but I want to get @imonroe's thoughts on this as well. Could there be a potential issue with removing these? IE: Change the default setting and have all fields go away all of a sudden?

**Comment by pookmish** [comment]
Removing the third party settings basically results in the same outcome as the `public` settings. The tests would have caught any issues with fields disappearing.

This PR is a result of implementing https://github.com/SU-SWS/stanford_profile_helper/pull/26. After a config import occurs (site install), it saves all the field storage entities which then runs through the hook in the profile helper. The profile helper removes the third party setting and then I exported the config. This is a result of that.

**Comment by imonroe** [comment]
I can't think of any immediate objections to this, but it also seems to me like just a little housekeeping.  I'm not sure we're getting any benefit besides parsimony, but that's probably enough to make it worthwhile.  I say thumbs-up.

**Review by imonroe — APPROVED** [review]

**Pull request merged**
