### PR TITLE
D8CORE-3749 Publication CSV importer

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Publication CSV importer
- see https://github.com/SU-SWS/stanford_publication/pull/51
- see https://github.com/SU-SWS/stanford_migrate/pull/36

# Need Review By (Date)
- 9/30

# Urgency
- high

# Steps to Test
1. `composer require su-sws/stanford_profile:dev-D8CORE-3749 su-sws/stanford_migrate:'dev-D8CORE-3749 as dev-8.x-1.x' --no-update`
2. `composer update -n`
3. `drush cr`
4. `blt drupal:update` or `drush cim -y`
5. navigate to `/admin/structure/migrate/manage/default/migrations/stanford_publications/csv-upload`
6. download a template csv and fill out some rows
7. upload the file
8. Run the importer either via the UI at `/admin/structure/migrate/manage/default/migrations/stanford_publications/execute` or drush `drush mim stanford_publications`
9. view the page `/admin/content` and validate your data with the imported content.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Review by imonroe — COMMENTED** [review]
So, I had to do a little dependency juggling to get this to install, but after creating branches in `stanford_events` and `stanford_person` it installed correctly.  I downloaded the CSV template and tried filling it in.  I uploaded the CSV successfully, and it imported my items.  However, when I went to view the items it imported, I get: 

image

**Comment by imonroe** [comment]
This was my test data

[Untitled spreadsheet - stanford_publications.csv](https://github.com/SU-SWS/stanford_profile/files/7227712/Untitled.spreadsheet.-.stanford_publications.csv)

**Comment by pookmish** [comment]
Your citation type in your data is incorrect. use one of these options:
```
su_article_newspaper
su_book
su_article_journal
su_other
su_thesis
```

I'll add some logic to the config to validate that though.

**Comment by pookmish** [comment]
The dependency thing was probably because i had a typo in the first test step.

**Comment by imonroe** [comment]
I'll try it with corrected data.

**Comment by imonroe** [comment]
I've tested this again locally, with updated data.  It imported my data correctly, and created the publications as I would expect.  I found a couple of things to point out.

The date fields -- I entered a publication date of 2/31/2021, which obviously doesn't exist, and it accepted it fine.  I notice only the year is displayed on the publication page, however, whether the date is correct or impossible.  I'm sure that's by design, but I'm not sure if we're storing that information for future use or just because.

The other thing I notice is that if you enter more than one topic term, separated by commas, they are all treated as a single term, and created in drupal as such.  I suggest having it parse that field for comma-separated values and create them as different terms.  

Other than that, works great!

**Comment by pookmish** [comment]
> The date fields -- I entered a publication date of 2/31/2021, which obviously doesn't exist, and it accepted it fine. I notice only the year is displayed on the publication page, however, whether the date is correct or impossible. I'm sure that's by design, but I'm not sure if we're storing that information for future use or just because.

Different publication types accept different levels of date granularity. Books, for example, only take a year, while articles take a full date.

> The other thing I notice is that if you enter more than one topic term, separated by commas, they are all treated as a single term, and created in drupal as such. I suggest having it parse that field for comma-separated values and create them as different terms.

This is [possible using vertical pipes](https://github.com/SU-SWS/stanford_profile/pull/456/files#diff-afd4b2eae24aaa1c9f212a21360f3a7c0536918700f69c1c1397c0d1f9950fc9R130). I go that direction because occasionally a comma is desired as part of the taxonomy term. You can see that happening on the [authors](https://github.com/SU-SWS/stanford_profile/pull/456/files#diff-afd4b2eae24aaa1c9f212a21360f3a7c0536918700f69c1c1397c0d1f9950fc9R197) as well.

**Pull request merged**
