### PR TITLE
D8CORE-1722: Basically remove everything code related from this profile.

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW 

# Summary
- Removes sub-modules and swaps them out for a helper module.

# Needed By (Date)
- July 8th

# Urgency
- Medium / High

# Steps to Test

1. Set this profile as the branch in cardinalsites stack
2. Run `composer update`
3. Run `blt di`
4. Run tests to validate everything is still in place

### Part 2.
- Review the code on https://github.com/SU-SWS/stanford_profile_helper branch 8.x-1.x

# Affected Projects or Products
- Everything ACSF

# Associated Issues and/or People
- D8CORE-1722

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
> Is the new `stanford_profile_helper` module going to be the place to put acceptance tests going forward?

Yeah, Probably should move some of those tests over as well.

**Comment by pookmish** [comment]
you could just copy instead of moving the tests. nothing hurt by having them in two places

**Comment by pookmish** [comment]
There are failing tests in the helper module though.

**Comment by imonroe** [comment]
Looks like the helper module is failing tests because it needs another module added to the composer.json:
```
Unable to install modules: module 'stanford_profile_helper' is missing its   
 
  dependency module admin_toolbar. 
```

**Comment by sherakama** [comment]
SU-SWS/stanford_profile_helper#1 merged. Thanks for that work.

**Pull request merged**
