### PR TITLE
D8CORE-933: screen reader only text for describing WYSIWYG paragraphs

### PR DESCRIPTION
**Pull request by cjwest**
# READY FOR REVIEW

# Summary
Based on input from Level Access, the visual styles in our WYSIWYG do not lend themselves to screen reader. This adds text that describes the various paragraph types when accessed by the screen reader.

# Needed By (Date)
6/9/2020

# Urgency
Not urgent

# Steps to Test

1. Check out the branch
1. Using the WYSIWYG create paragraphs for each style in the WYSIWYG
2. Using a screen reader, listen for descriptions of each paragraph

Please give feedback on the text I included. 

I would really like to have this put up for Ishi and @kerri-augenstein  to experience, and for review by Level Access.

# Affected Projects or Products
D8Core

# Associated Issues and/or People
- JIRA ticket: https://stanfordits.atlassian.net/browse/D8CORE-933
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
This looks neat. Can you bring it up at MOA or Dev chat. This looks like a good learning lesson for everyone.

**Comment by sherakama** [comment]
@cjwest I pushed up a build here: https://amptesting-test.sites.stanford.edu/
Please have a review.

**Comment by cjwest** [comment]
Thank you, @sherakama !

Here's [demo video](https://stanford.zoom.us/rec/play/6JAlJOCrqz43SN2UtwSDVvZ-W9Xofaqs13JP-PAKyk7gVnNSMFCvZ7cRNLB6Eb7AHFH8y-dudqgoS0Sm?_x_zm_rhtaid=207&_x_zm_rtaid=TXODvB6mSPWUqy9hdosyMw.1591232349129.9ed49eb8e42dbb1b928a7a7a6d129f8b&autoplay=true&continueMode=true&startTime=1591231944000) of how it works!

**Comment by cjwest** [comment]
Thank you, @sherakama. I put up a test page here:
https://amptesting-test.sites.stanford.edu/interior-page/wysiwyg/demonstrate-styles

**Comment by sherakama** [comment]
@cjwest you mentioned in an earlier chat you would like to get feedback on the terms/language used for this. What are your next steps?

**Comment by cjwest** [comment]
@sherakama,
Thanks for checking in on this. 
I will be attending SOAP office hours on Tuesday 6/9. It's the first thing we'll go over. 
Otherwise, I think it's GTG. 

_I do want to be mindful and avoid the mishap with the stacking buttons._

**Comment by sherakama** [comment]
@cjwest Please resolve the compiled conflicts.

**Comment by cjwest** [comment]
@sherakama, Fixed! Thanks for pointing this out!

**Pull request merged**
