### PR TITLE
Created a config split for acsf modules

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Move acsf modules to an acsf config split.

# Need Review By (Date)
- later time is fine.

# Urgency
- low

# Steps to Test
1. using https://github.com/SU-SWS/acsf-cardinalsites/pull/94 verify the modules are still enabled on acsf environments.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
So this is just another split to have an `all acsf` env?

**Comment by pookmish** [comment]
yep. stanfordgryphon was trying to enable the modules that weren't there and i realized it didn't need to be.
We could even go one step further and create an `ah_other` ([any acquia](https://github.com/acquia/blt/blob/12.x/settings/config.settings.php#L77)) and move the acquia purge module into there. but i think we're ok as is for now

**Comment by sherakama** [comment]
Ok, lets hold on this till next week.

**Comment by pookmish** [comment]
i was thinking the same thing. i'm using this branch on gryphon now so its not a blocker.

**Comment by pookmish** [comment]
should we revisit this again?

**Comment by sherakama** [comment]
> Should we revisit this again?

Yeah, looks like with the Paranoia work that John is putting in we will likely need something like this. I want to take a step back this week and give it a hard think as we have several needs with upgrade paths, acsf locking, shared profiles and more, that are a part of this.

**Pull request merged**
