### PR TITLE
D8CORE-971: Update gutter between content and sidebar for stanford_page.

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
Adjust the space between the aside and the main content on Stanford pages 

# Needed By (Date)
- RC1

# Urgency
- Nice to have?

# Steps to Test
- Checkout this branch
- Verify that for breakpoints xl and larger, there's an extra 150px between the main content and the side bar.

## Smaller than xl
Screen Shot 2019-12-20 at 7 58 25 PM

## XL
Screen Shot 2019-12-20 at 7 58 58 PM

## XXL
Screen Shot 2019-12-20 at 7 59 19 PM

# Affected Projects or Products
D8Core

# Associated Issues and/or People
- JIRA ticket
https://stanfordits.atlassian.net/browse/D8CORE-971

- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by cjwest** [comment]
I confirmed it works as expected and that the code is showing up in the profile.
Thanks for all your help on this, @sherakama !

**Comment by cjwest** [comment]
Hey @sherakama, it looks like I don't have the privileges needed to merge this.

Screen Shot 2020-01-20 at 5 43 33 PM

**Comment by sherakama** [comment]
@cjwest you need to approve it first. 

Go to the "file changes" page (https://github.com/SU-SWS/stanford_profile/pull/65/files), click on the green "Review changes" button and select approve. Then you can merge.

**Comment by sherakama** [comment]
Screen Shot 2020-01-23 at 11 13 57 PM
Screen Shot 2020-01-23 at 11 14 04 PM


Turns out that this created some weirdness with the layout when there is no sidebar.

**Comment by sherakama** [comment]
Re-opening the JIRA ticket for round 2 at this.

**Pull request merged**
