### PR TITLE
D8CORE-3523: Added User Search form

### PR DESCRIPTION
**Pull request by imonroe**
# READY FOR REVIEW

# Summary
- Added a new form for searching users of a site based on name, role, or whether the account is active or not.

# Needed By (Date)
- 5/6/21

# Urgency
- medium

# Steps to Test

1. Checkout this branch.
2. `drush cim` 
3. You should now see a new entry under the `People` menu for `User Search`.  Use that button, or navigate manually to `/admin/people/user-search`
4. Verify the user search works with various options.

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Review by jenbreese — CHANGES_REQUESTED** [review]
It doesn't look right: the dropdown is showing all the options. 
Screen Shot 2021-05-05 at 2 03 48 PM

**Comment by imonroe** [comment]
Yeah, that's the widget that Views provides for that field.  I'll see if I can figure out a way to change it.

**Comment by jenbreese** [comment]
Oh cool.  Yah it would be nice we if we could change it.

**Comment by jenbreese** [comment]
Looks way better.  Thanks @imonroe. I'll approve and merge when the tests pass.

**Review by jenbreese — APPROVED** [review]

**Pull request merged**
