### PR TITLE
8.1.0-alpha3

### PR DESCRIPTION
**Pull request by jbickar**
https://github.com/SU-SWS/stanford_profile/compare/8.1.0-alpha.2...tag-8.1.0-alpha3

Needed for https://github.com/SU-SWS/acsf-cardinalsites/pull/48

I'm not sure of the wording of everything in the CHANGELOG.

This can wait until after Winter Closure.

### CODE REVIEW

**Comment by sherakama** [comment]
It would be nice to get this out before the break.

**Comment by jbickar** [comment]
I thought I saw the Environment Indicator work get merged into 8.x-1.x yesterday. Maybe a hotfix for the CHANGELOG for this release?

**Comment by sherakama** [comment]
Sure, edit and force push the tag.

**Pull request merged**
