### PR TITLE
D8CORE-2856 Add list and entity reference paragraph types

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Created entity reference and view reference paragraph types
- Stubbed out starting point for a "Card" display for each paragraph type. These will be revised later
- Limited the views to only a few choices that I assume are the best at this time.

# Need Review By (Date)
- 10/19

# Urgency
- medium

# Steps to Test
1. checkout this branch and the same branch in https://github.com/SU-SWS/stanford_profile_helper/pull/34
1. `composer require drupal/viewfield` (it's easier this way than doing all the different requirements)
1. `blt drupal:update` or `blt drupal:install -n`
1. Create a basic page and use the "Lists" or "Content Reference" paragraph types.
1. verify they work close to what you'd expect.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

see https://github.com/SU-SWS/stanford_profile_helper/pull/34

### CODE REVIEW

**Comment by sherakama** [comment]
Running an install now but the tests are passing to this is likely fine.

Do you want to move the new view modes down into the child projets? Eg: the news and events card views down into the news/events modules?

**Comment by pookmish** [comment]
`:meh:` :shrug: I'm indifferent about moving them down into the modules. I'd say at least at this point let's wait. I'm sure some tweaks will come to the card displays. at that time we can decide if it's worth that effort.

**Comment by sherakama** [comment]
> `:meh:` 🤷 I'm indifferent about moving them down into the modules. I'd say at least at this point let's wait. I'm sure some tweaks will come to the card displays. at that time we can decide if it's worth that effort.

Ticket!

**Comment by pookmish** [comment]
https://stanfordits.atlassian.net/browse/D8CORE-2869 for future sprints

**Comment by sherakama** [comment]
Screen Shot 2020-10-16 at 10 16 19 AM

**Comment by sherakama** [comment]
Probably should add some no content text to the views.

Also, do we want to only allow 1 per row? They get kinda squishy when put side by side.

**Comment by pookmish** [comment]
> Probably should add some no content text to the views.

I was thinking we could either do that and also have a behavior checkbox that says "Hide all fields if the list is empty". It would end up being an empty space but maybe we can help with that. :shrug:

**Review by sherakama — APPROVED** [review]
Ok, sounds like you got this covered. I will mark as approved and let you merge when you are good and ready.

**Pull request merged**
