### PR TITLE
D8CORE-1351: Add Paranoia

### PR DESCRIPTION
**Pull request by jbickar**
# READY FOR REVIEW

# Summary
- See https://github.com/SU-SWS/acsf-cardinalsites/pull/98 - needed for adding Paranoia so that config sync will work.

# Review By (Date)
- Friday, March 13

# Urgency
- Needed for Paranoia. End of sprint would be nice.

# Steps to Test

1. Check out `D8CORE-1351` of the cardinalsites stack.
2. `composer install` (or `composer nuke`)
3. `blt di`
4. Ensure that Drupal installs correctly

# Affected Projects or Products
- D8CORE

# Associated Issues and/or People
- JIRA ticket: D8CORE-1351
- Other PRs: https://github.com/SU-SWS/acsf-cardinalsites/pull/98

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by jbickar** [comment]
Not sure why these tests are failing. Sounds like a problem for Monday John.

**Comment by jbickar** [comment]
Y U stuck, CircleCI?

**Comment by jbickar** [comment]
Failed tests from the [last CircleCI run](https://circleci.com/gh/SU-SWS/stanford_profile/1640?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) for my reference:

```

--- Failed scenarios:

    /var/www/html/web/profiles/custom/stanford_profile/tests/behat/features/Paragraphs/WYSIWYG.feature:7
    /var/www/html/web/profiles/custom/stanford_profile/tests/behat/features/Paragraphs/WYSIWYG.feature:77
    /var/www/html/web/profiles/custom/stanford_profile/tests/behat/features/Paragraphs/WYSIWYG.feature:106
    /var/www/html/web/profiles/custom/stanford_profile/tests/behat/features/Paragraphs/WYSIWYG.feature:136
    /var/www/html/web/profiles/custom/stanford_profile/tests/behat/features/Users/DefaultUsers.feature:7
    /var/www/html/web/profiles/custom/stanford_profile/tests/behat/features/Users/Roles.feature:7
```

The `Users` features pass on my local.

**Comment by sherakama** [comment]
Seems like it is passing now?

**Comment by jbickar** [comment]
Yeah, passed now. Ready for review.

**Comment by jbickar** [comment]
https://github.com/SU-SWS/acsf-cardinalsites/pull/98/files#diff-42bcfe08dc8fea00dc64f4500fcbda22R37

**Comment by pookmish** [comment]
That won't work on acsf. config management trumps `blt.yml` settings. you'll have to put the enabling into the config split for the environments. and the `paranoia.settings.yml` will go into the stack repo in their respective envs. https://github.com/SU-SWS/acsf-cardinalsites/tree/1.x/config/envs

**Comment by jbickar** [comment]
OK, thanks. Per our conversation yesterday, I'm still trying to parse how the config splits, the profile, and `blt.yml` interact.

I will update.

**Comment by pookmish** [comment]
So with lelandd8 the `[profilename].info.yml` and `blt.yml` are more important. But since this profile is using config management, everything has to be explicitly defined in the configs.

**Comment by jbickar** [comment]
> you'll have to put the enabling into the config split for the environments

I thought the _enabling_ was done in `blt/blt.yml`? Where does it go?

I'm not defining config for Paranoia (just relying on the default), so there is no `paranoia.settings.yml` file to go in `config/envs/*`. Unless that's required.

**Comment by pookmish** [comment]
https://github.com/SU-SWS/stanford_profile/blob/8.x-1.x/config/sync/config_split.config_split.prod.yml#L9
Just add it to the modules array and it'll split the module and it settings.
The `paranoia.settings.yml` will still have to go in the directory even if you use default. otherwise the config will not live on the site at all and the module might throw errors.

**Comment by jbickar** [comment]
OK, I will do that and add it to the README.

**Comment by jbickar** [comment]
So should paranoia live in the `composer.json` here or in acsf-cardinalsites?

**Comment by jbickar** [comment]
OK, should be ready for review again. Per our conversation earlier today:

1. Enable paranoia in profile config splits (done in this PR)
2. Move paranoia to profile composer.json (done in this PR)
3. paranoia.settings.yml goes in config/envs on stack (see [this](https://github.com/SU-SWS/acsf-cardinalsites/pull/98/files#diff-9ca81c4c35f96f9a597864952b87954aR1) for example)
4. Remove paranoia from blt.yml (it is no longer part of https://github.com/SU-SWS/acsf-cardinalsites/pull/98)
5. `user_role_load()` is deprecated - use `Role::load()` (done; see [this](https://github.com/SU-SWS/acsf-cardinalsites/pull/98/files#diff-fd60013443875760f51f19e73ad9d782R20) and other examples in that PR)
6. Update patch in composer.json (done, see [this](https://github.com/SU-SWS/acsf-cardinalsites/pull/98/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R245))

**Comment by jbickar** [comment]
I suppose I should move the Paranoia patch and tests from the stack into this repository?

**Comment by jbickar** [comment]
Per discussion, not really needed to move the Paranoia patch and tests from the stack into here.

**Pull request merged**
