### PR TITLE
D8CORE-6974 | @jdwjdwjdw | Update local footer config userguide links

### PR DESCRIPTION
**Pull request by jdwjdwjdw**
# READY FOR REVIEW

# Summary
- [D8CORE-6974](https://stanfordits.atlassian.net/browse/D8CORE-6974): BUG // Fix broken link on Local Footer page

# Review By (Date)
- EOD 10/19 (before code freeze)

# Urgency
- High

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to the `Local Lockup` section at `/admin/config/system/local-footer` and confirm the userguide links work correctly and the updated text looks good.
3. Review code 🕸️

# Associated Issues and/or People
- [D8CORE-6974](https://stanfordits.atlassian.net/browse/D8CORE-6974): BUG // Fix broken link on Local Footer page

[D8CORE-6974]: https://stanfordits.atlassian.net/browse/D8CORE-6974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[D8CORE-6974]: https://stanfordits.atlassian.net/browse/D8CORE-6974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by pookmish — APPROVED** [review]
Looks good.

**Comment by pookmish** [comment]
DO not merge with failing tests. this is a rule

**Comment by pookmish** [comment]
@jdwjdwjdw we don't merge with failing tests. especially with all tests failing. please keep this in mind.

**Comment by jdwjdwjdw** [comment]
@pookmish noted, sorry about that. I assumed that since it was approved this was a situation we could ignore those.

**Pull request merged**
