### PR TITLE
D8CORE-1514 Add administer media permission to site managers

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Added administer media permission for site manager and higher

# Need Review By (Date)
- 3/19

# Urgency
- medium

# Steps to Test
1. Checkout this branch
1. drush cim -y
1. log in as a site manager
1. verify you have access to the media list at `/admin/content/media`

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
This one has the same issue as #151 

```
│
    ╳  unexpected alert open: {Alert text : }
    ╳    (Session info: chrome=74.0.3729.108)
    ╳    (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.15.0-1052-aws x86_64) (WebDriver\Exception\UnexpectedAlertOpen)
    │
    └─ @AfterStep # StanfordBehat\DrupalExtension\Context\SwsContext::afterStepFailure()
      unexpected alert open: {Alert text : }
  (Session info: chrome=74.0.3729.108)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.15.0-1052-aws x86_64)
```

**Comment by sherakama** [comment]
Code looks fine after we figure out what is going sidewise in the behat tests.

**Comment by pookmish** [comment]
https://github.com/SU-SWS/react_paragraphs/pull/29 should fix those failures. Something wierd happens with the tab index attribute on the dialogs

**Comment by sherakama** [comment]
Unfortunately, this is still failing with the 8.1.6 release.

**Comment by pookmish** [comment]
I think it was just a gremlin. i re-ran them and they be passing now.

**Pull request merged**
