### PR TITLE
D8CORE-5278 Added scheduler module and configured for all content types

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- D8CORE-5278 Added scheduler module and configured for all content types

# Need Review By (Date)
- 2/30

# Urgency
- medium

# Steps to Test
1. `composer require su-sws/stanford_profile:dev-D8CORE-5278 --no-update; composer update -n`
2. `blt drupal:update` or `blt di -n`
3. create a node and configure the scheduler to publish in the future. (1 minute would be enough)
4. wait for the time to pass
5. run cron `drush cron`
6. view your node and verify it is now published.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by imonroe** [comment]
Followed the instructions for installation, and created a basic page.  Scheduling options shows up as expected.  Set publishing time, waited, ran `cron`, but it didn't publish.
Things I also tried: 
- Marked as published with publishing time in the future, ran cron, but it didn't publish.
- ran cron via CLI and via web interface, but still no dice.
- changed time to an hour prior to see if it was something about the timezone.  ran cron, still didn't publish.

Looks like it should work, but it's just not publishing correctly for me on my local.  

Anything I might be missing?

**Comment by imonroe** [comment]
weird..  I installed https://github.com/SU-SWS/stanford_profile_helper/pull/174 to check as well, and now it seems to work.  At least, the `drush cron` command returns a notice saying the page was scheduled, and it did in fact publish it.

**Comment by pookmish** [comment]
It might have just been timing. Ultimate cron sometimes prevents it from running too frequent.

**Review by imonroe — APPROVED** [review]
Works for me now.  Includes test which passes.

**Review by imonroe — APPROVED** [review]
Looks good.

**Comment by pookmish** [comment]
I'll review why the test is failing and see if i can make it more reliable.

**Pull request merged**
