### PR TITLE
D8CORE-6953: Additional edits to the editing buttons

### PR DESCRIPTION
**Pull request by jenbreese**
# READY FOR REVIEW

# Summary
- Made some updates to the first pass at the button edits. 
- https://github.com/SU-SWS/stanford_profile/pull/720

# Review By (Date)
- 10/12

# Criticality
- Normal

# Urgency
- Normal

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Navigate to a node page. 
4. Verify the editing tabs look correct again

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory? NO

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
[- D8CORE-6953](https://stanfordits.atlassian.net/browse/D8CORE-6953)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by pookmish** [comment]
Three are a couple issue still that need to be addressed. Below 600 pixel window width cause a gap above. Between 600 and 760 the admin toolbar overlaps the items.
image

image

**Comment by jenbreese** [comment]
When you have time, will you take another look? Thank you!

**Comment by pookmish** [comment]
Can we just get rid of the sticky on mobile all together? The things take up almost half the screen when on a viewport that matches an iphone 11: 414x896

Plus there are just too many scenarios that the sticky doesn't work well.

I also found this one situation that really breaks things. 806 wide screen and the admin toolbar is open. 
image

**Comment by jenbreese** [comment]
Sure, would this be the idea for adding/removing the sticky class? 
`if ((window.pageYOffset >= sticky - toolbarHeight) && (window.innerWidth >= 991)) {`

**Comment by pookmish** [comment]
> Sure, would this be the idea for adding/removing the sticky class? `if ((window.pageYOffset >= sticky - toolbarHeight) && (window.innerWidth >= 991)) {`

I don't know where you refer to that. It should just be setting `position:relative` to the tabs while on mobile.

**Comment by jenbreese** [comment]
@pookmish Ok, It is good to look at now.

**Comment by pookmish** [comment]
Thanks. I think this is good enough. There's still one situation that it doesn't look good, but lets move on to the other tickets that need fixing.

**Pull request merged**
