### PR TITLE
D8CORE-2937: making the person title an h4 for accessibility

### PR DESCRIPTION
**Pull request by jenbreese**
# NOT READY FOR REVIEW
@pookmish and I agreed to put this in holding for the time being.

# Summary
- Changing the person name on the person grid to be an `h4`. 

# Review By (Date)
- 8/1

# Criticality
- Med - accessibility
- Affects the People grid which is all sites using it.
- Affects the Person List

# Urgency
- Med

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Checkout the CSS changes: https://github.com/SU-SWS/stanford_person/pull/149
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Navigate to /People page and a filtered page. 
4. Verify there is no visible difference but you see the `h4` in the code.
4. Create a people list
5. Verify there is no visible difference but you see the `h4` in the code.

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory? Yes
- https://github.com/SU-SWS/stanford_profile/pull/438

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [x] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [x] Manual accessibility: Manually tested? Or, [D8CORE-4666](https://stanfordits.atlassian.net/browse/D8CORE-4666)

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- People Module

# Associated Issues and/or People
- [D8CORE_2937](https://stanfordits.atlassian.net/browse/D8CORE-2937)
- https://github.com/SU-SWS/stanford_profile/pull/438
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- @rebeccahongsf I tried the change on SAA Victoria and saw no change.

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by pookmish** [comment]
@jenbreese Can you fill out the PR information please.

**Comment by jenbreese** [comment]
Whoops. Yes, I will.

**Comment by pookmish** [comment]
Why an `<h4>`? There's no `<h2>` or `<h3>` tags on those list pages to structure the content.
Also i'd prefer _if_ this change is done to not do it in the rewrite field. It can be done on the title field directly 
image

**Comment by jenbreese** [comment]
I did the 'h4' since that was the request from @cjwest on the ticket. I was curious what others were doing so I looked at [UC Berkeley](https://complit.berkeley.edu/people/faculty) and they are using `h3` for Professor names. If we want headings, then maybe `h2` is better so it is sequential like recommended.

**Comment by pookmish** [comment]
https://www.w3.org/TR/2012/NOTE-WCAG20-TECHS-20120103/G141

> To facilitate navigation and understanding of overall document structure, authors should use headings that are properly nested (e.g., h1 followed by h2, h2 followed by h2 or h3, h3 followed by h3 or h4, etc.).

**Comment by jenbreese** [comment]
@pookmish and @cjwest, I suggest we remove this PR and the [CSS support one](https://github.com/SU-SWS/stanford_person/pull/149) for consideration at this time. It seems like further exploration is needed.

**Comment by cjwest** [comment]
Hi @jenbreese,

I apologize for misleading you on this one. In the [ticket](https://stanfordits.atlassian.net/browse/D8CORE-2937) I had made the suggestion:
> Change the <div> that wraps the person's name to an <h3> or <h4>.

The reason I didn't exactly specify one or another was because we need to make sure the heading level makes sense within the page. See https://www.w3.org/WAI/tutorials/page-structure/headings/

For a views page, we know that the the title of the view will be an `<h1>` so that any subsequent headings should be  at most `<h2>`. For a block on a page we know that the `<h1>` will be the title of the page, and the title of the view will be `<h2>` so subsequent headings will be at most `<h3>`. I've seen instances where the filter is an `<h3>` and the subsequent headings begin with `<h4>`. It depends on how it's used on the page. 


In this case, looking at the placement of the block on the page, it looks like it should be `<h3>`

Screen Shot 2021-07-29 at 1 15 49 PM

**Comment by jenbreese** [comment]
@pookmish and @cjwest I saved your comments in the original ticket and closing this pull request as a won't do. I will make new pull requests that follow your guidelines.

**Pull request closed without merging**
