### PR TITLE
D8CORE-943 Added more image styles for wysiwyg

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Added more image styles to be allowed in the wysiwyg.

# Need Review By (Date)
- 3/13

# Urgency
- low

# Steps to Test
1. checkout this branch
1. drush cim
1. in a wysiwyg embed an image
1. choose from the various styles
1. verify they do what you'd think they should do.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by pookmish** [comment]
poke

**Comment by sherakama** [comment]
Test to validate the options show up?

**Comment by pookmish** [comment]
maybe a test to see if the entity display shows. but checking in the wysiwyg is difficult until we get codeception setup to easily have a wysiwyg to do that.

**Comment by sherakama** [comment]
Yeah, just something to validate that the options are enabled.

**Comment by pookmish** [comment]
green lights on the tests

**Comment by sherakama** [comment]
> green lights on the tests

Thank you very much.

**Pull request merged**
