### PR TITLE
Add and configure search api module to replace core search.

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Use search api to replace core search functionality

# Need Review By (Date)
- no rush

# Urgency
- low

# Steps to Test
1. `composer require su-sws/stanford_profile:dev-search-api --no-update`
2. `composer update -n`
3. `drush cim -y; drush cr; drush cron`
4. try the site search
5. verify it returns some results that you'd expect and is has some decent formatting to it.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Review by sherakama — APPROVED** [review]
OK.

**Comment by sherakama** [comment]
Nice to see this coming through. Huge improvement on core search.

**Comment by pookmish** [comment]
improved

**Review by imonroe — CHANGES_REQUESTED** [review]
This appears to work correctly for me when I search using the page at `/search` and returns results like I would expect.  However, it does not seem to work with the search form in the header section of the page.  It reloads the current page with the following: `?key=research&search=` appended to the URL.

I believe instead it should send you to `/search?key=research` or whatever the key is that you've searched for. 

Tested with the `search-api` branch in stanford_profile_helper`

**Comment by pookmish** [comment]
Oh yeah i've seen that before. how did i fix that in the past... :thinking: 

This PR isn't urgent and certainly can wait so i'll come back to it next week maybe.

**Comment by pookmish** [comment]
Ok I fixed the form submission path issue with a recent commit to stanford_profile_helper. This should be ready for testing again.

**Review by imonroe — APPROVED** [review]
This works correctly for me.  I get an extra querystring of `search`, but that's not a big deal; it's just the name of the submit button field sent via GET.  `composer.json` need a revert and there's a merge conflict that needs to be addressed, but other than that, G2G.  The styles in stanford_profile_helper have been merged.

**Pull request merged**
