### PR TITLE
D8CORE-4246 Add fontawesome module for wysiwyg icon support

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Add the fontawesome module so that the icons display in the wysiwyg

# Need Review By (Date)
- 11/19

# Urgency
- medium

# Steps to Test
1. `composer require su-sws/stanford_profile:dev-D8CORE-4246`
2. `blt drupal:update` or `blt drupal:install`
3. create a page with a text area
4. fill the text area with some text like `<p class="fab fa-drupal">This is some text</p>`
5. view the ckeditor in normal style and verify the icon displays while editing.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by jenbreese** [comment]
Is there another step to be done? I did the ones in this PR and the ones in https://github.com/SU-SWS/stanford_basic/pull/256. I'm not getting what I think you want. 
This is what I am seeing.
Screen Shot 2021-11-10 at 3 54 35 PM

**Comment by pookmish** [comment]
> Is there another step to be done? I did the ones in this PR and the ones in [SU-SWS/stanford_basic#256](https://github.com/SU-SWS/stanford_basic/pull/256). I'm not getting what I think you want. This is what I am seeing. Screen Shot 2021-11-10 at 3 54 35 PM

You might have to clear your caches to accept the font styles. the word `Stuff` should have the same font styling as the other text on that page.

**Comment by pookmish** [comment]
Oh thanks @jenbreese i see that i have to do the inherit on the `font-weight` as well.

**Comment by jenbreese** [comment]
The weight problem is fixed.  It is a little weird to use. 
Here is the Source view.
Screen Shot 2021-11-10 at 4 49 29 PM

If you press return, you don't get a line return,  you get another icon. Maybe solvable with documentation?
Screen Shot 2021-11-10 at 4 49 15 PM
Screen Shot 2021-11-10 at 4 47 24 PM

**Comment by pookmish** [comment]
Yeah the issue you are seeing appears to just be a CKEditor "Feature". Because the FA classes are a more advanced thing, I'm not too concerned about it existing, but we can document it.

**Comment by jenbreese** [comment]
Great. I'll merge it.

**Review by jenbreese — APPROVED** [review]
GTG

**Pull request merged**
