### PR TITLE
D8CORE-4194 Add url text for the link on media w caption paragraph

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Make media with caption link title required.
- https://github.com/SU-SWS/jumpstart_ui/pull/101
- https://github.com/SU-SWS/stanford_profile_helper/pull/126

# Need Review By (Date)
- 6/3

# Urgency
- medium

# Steps to Test
1. checkout this branch
2. checkout the branch in https://github.com/SU-SWS/jumpstart_ui/pull/101
3. checkout the branch in https://github.com/SU-SWS/stanford_profile_helper/pull/126
4. (optional) sync to amptesting. `drush sql:sync @amptesting.01test @self`
3. `blt drupal:update`
4. `drush cr`
5. Create a basic page and put a "Media with Caption" on it
6. Populate the link field
7. view the page and verify the image is "clickable"
8. verify the screen reader reads the link and the image separately.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by cjwest** [comment]
@pookmish,
I put some comments in the ticket.

**Comment by cjwest** [comment]
Sanity check, @pookmish - I see that this is marked "ready for review". Is that accurate?

**Comment by cjwest** [comment]
@pookmish,
I want to know when to review this ticket.
Do you want to mark this as "Not ready for review" or should I take my name off?

**Comment by cjwest** [comment]
I took my name off of this PR. When it's GTG, feel free to assign it to me.

**Comment by pookmish** [comment]
@cjwest I've updated the testing steps to include the PR in https://github.com/SU-SWS/stanford_profile_helper/pull/126

Please review when you can. 
image

**Review by cjwest — APPROVED** [review]

**Comment by cjwest** [comment]
Very nice. Works as expected.

**Pull request merged**
