### PR TITLE
changed the widget for the media library form mode on images

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

See https://github.com/SU-SWS/acsf-cardinalsites/pull/49

### CODE REVIEW

**Comment by pookmish** [comment]
Which dependent pr? All tests look to have passed for some time now

**Comment by sherakama** [comment]
manual linky clicky of SU-SWS/acsf-cardinalsites#49.

**Comment by sherakama** [comment]
> Theme hook focal_point_media_library_image_widget not found.

Currently troubleshooting this.

**Comment by sherakama** [comment]
Seems this is just a cache issue and goes away.

Steps to reproduce. 
1. Build new site
2. Log in 
3. Go to node edit page for homepage
4. Review logs

Clear the cache and repeat above and no log.

**Pull request merged**
