### PR TITLE
D8CORE-1200 Additional permission check for deleting home page

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- I built out this test, so we might as well use it. It verifies the user can't bulk delete the home page.

# Need Review By (Date)
- 10/5 i guess

# Urgency
- low

# Steps to Test
1. View the tests.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Review by sherakama — APPROVED** [review]
GTG on green lights.

**Comment by pookmish** [comment]
yeah to get full green lights might take awhile since it's related to some deep underlying dependency

**Comment by sherakama** [comment]
> yeah to get full green lights might take awhile since it's related to some deep underlying dependency

Could be related.
https://www.drupal.org/project/upgrade_status/issues/3172382

**Comment by pookmish** [comment]
That issue seems to be the same. But it's not specific to upgrade_status. see https://github.com/mglaman/drupal-check/issues/186#issuecomment-696856219
I was able to use `phpstan/phpstan:0.12.42` and no issues. maybe we lock caravan to that version for now? what do you think?

**Comment by pookmish** [comment]
Cool. green lights now

**Pull request merged**
