### PR TITLE
D8CORE-3565: changing the more publication to not filter on taxonmy

### PR DESCRIPTION
**Pull request by jenbreese**
# READY FOR REVIEW

# Summary
- Removed the extra filter on the More Publication cards on the Node page.

# Needed By (Date)
- 2/26

# Urgency
- Med

# Steps to Test

1. Pull in this change.
2. Verify that the node page has all the newest publications in the More Publications, rather than only the ones with the same taxonomy.

# Affected Projects or Products
- D8CORE-3565

# Associated Issues and/or People
- D8CORE-3565
- 
# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by imonroe** [comment]
So there are merge conflicts with the view configuration here.  @jenbreese can you please resolve?

**Review by imonroe — CHANGES_REQUESTED** [review]
resolve merge conflict

**Comment by jenbreese** [comment]
@imonroe Too many changes happened. I'll make a new branch/pull request from 8.x-2.x

**Comment by jenbreese** [comment]
@imonroe New PR. https://github.com/SU-SWS/stanford_profile/pull/375

**Pull request closed without merging**
