### PR TITLE
D8CORE-3520 All Publications list page

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- created the /publications list page
- I had to put the default content here instead of the publications module because it relies on the paragraph type from the profile. So it doesn't work to put it into the module.

# Related PRS
https://github.com/SU-SWS/stanford_publication/pull/28
https://github.com/SU-SWS/stanford_profile_helper/pull/74

# Need Review By (Date)
- 3/3

# Urgency
- high

# Steps to Test
1. `composer require su-sws/stanford_profile:dev-D8CORE-3520 --no-update`
2. `composer update -n`
3. either `blt di -n` or `blt drupal:update` depending if you have an existing site
4. verify you have a `/publications` page created.
5. create some publication topic terms and some publication content. (devel generate works good)
6. ensure they show up on the /publications page.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by jenbreese** [comment]
@pookmish Woo, it worked. Thank you.

**Comment by imonroe** [comment]
I can't get this to install by following the instructions above.  Composer tells me it can't resolve to an installable set of packages.

**Review by imonroe — CHANGES_REQUESTED** [review]
Installed per instructions, generated publications via devel_generate (which is a real time saver), and the `/publications` page shows up.  However, I only get one publication result, listed over and over again:

image

I verified the publications all generated successfully, and the styling looks right.  It's just not showing the resulting list correctly.

**Comment by pookmish** [comment]
I'm going to merge this and the other 2 PRs.

**Pull request merged**
