### PR TITLE
D8CORE-1499: Multiple Per Row

### PR DESCRIPTION
**Pull request by jenbreese**
# READY FOR REVIEW
# Replacement for the Stanford Basic theme pull request. I moved it here per comments.

# Summary
- adjustments for the mulitparagraphs per row.

# Review By (Date)
- soonish

# Urgency
- high

# Steps to Test

1. Set up 4 per row: https://github.com/SU-SWS/stanford_profile/pull/159 : checkout that branch and run blt drupal:update and that'll give you the ability to have 4 per row
2. Pull in this branch.
3. Start adding content.
4. Try it out on the homepage/full width page
5. Try it on an interior page.
6. Try it on a page with a secondary navigation.

# Notes
1. I've tried it on Chrome/Mac, FF/Mac, Safari/Mac, IE, Edge.  There are some issues with FF on Mac and PC (browserstack)
2. I tried to not change any margins. I shrunk some set sizing when it overran out of the browser. In a design meeting, we thought stacking 4 across starting at LG would be helpful since it the paragraphs are so small.  

# Affected Projects or Products
- https://github.com/SU-SWS/stanford_profile/pull/159

# Associated Issues and/or People
- D8CORE-1499
- https://github.com/SU-SWS/stanford_profile/pull/159
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- @sherakama 

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by pookmish** [comment]
I'm going to rely on @sherakama to review this. I dont know if this was the expected changes

**Comment by jenbreese** [comment]
This is ready to be looked at again. I've tested on my Mac on FF, Chrome and Safari. I've tested on Broswerstack in IE, Edge and Chrome. I didn't adjust gutters. The only design changes were: 

- When the text boxes were overlaying at too narrow and too many in a row I moved the overlay over to the left edge.
- When text overran, I did overflow: hidden.

**Comment by jenbreese** [comment]
Updated to add gutters. It was simplest to add the gutters to the media caption as well. Tested on the same Mac and Windows browser at different responsive sizes. Ready for review.

**Comment by sherakama** [comment]
woo hoo. I'll start the review soon.

**Comment by sherakama** [comment]
@jenbreese feedback in the PR https://github.com/SU-SWS/stanford_profile/pull/178

**Comment by sherakama** [comment]
Also, I noted that cards are not going 4 across on inside (2 column) pages and the 4th card is wrapping down to another line.

**Comment by jenbreese** [comment]
@sherakama This is ready to check again. I mixed in the 1499b.  I fixed the media issue.

**Comment by pookmish** [comment]
I ran visual regression tests to compare a site created from the existing code on the stack compared to this and and the `8.x-1.x` branch and here's my observations:
1. this branch has little to no differences compared to `8.x-1.x`
1. both branches have some centering differences compared to existing code.

I don't know if this module is the cause of those differences but it should be reviewed. I uploaded the backstop test to a temporary location. https://heuristic-khorana-13951f.netlify.app/html_report/

**Comment by sherakama** [comment]
@pookmish Thanks for the visual regression tests. They look great overall. I think we can call this good and make whatever improvements we need to in the next release. Let's be sure to hit this hard on 'real live' sites in QA.

**Pull request merged**
