### PR TITLE
Replaced all deprecation functions and methods

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- House cleaning, removing any deprecated methods and function calls.

# Need Review By (Date)
- Need before Drupal 10

# Urgency
- low

# Steps to Test
1. Automated tests should be enough.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Review by imonroe — APPROVED** [review]
This looks good to me and can get merged when tests pass.  The deprecation of the `drupal_get_path` and `render` functions are going to throw me off the first few times I need to use them, that's for sure.

**Comment by pookmish** [comment]
Seems like the `render` method via the service doesn't do everything like the it does using the global `render` function all. I'm not sure how I feel about it at this time, but this is super low priority so I might sit on it for a bit.

**Comment by pookmish** [comment]
Removing Ian for now and marking as a draft. This will take some time.

**Comment by pookmish** [comment]
Closing in favor of https://github.com/SU-SWS/stanford_profile/pull/654

**Pull request closed without merging**
