### PR TITLE
D8CORE-1792: Enabled a11y_checker for text editor.

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW 

# Summary
- Adds the accessibility checker to the ckeditor wysiwyg
- SEE: https://github.com/SU-SWS/acsf-cardinalsites/pull/134 

# Review By (Date)
- April 7th

# Urgency
- Low

# Steps to Test

1.  SEE: https://github.com/SU-SWS/acsf-cardinalsites/pull/134
2. Review code.

# Affected Projects or Products
- D8CORE

# Associated Issues and/or People
- D8CORE-1792
- D8CORE-1490

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by pookmish** [comment]
What does this solve? As much as i tried to break it, i couldn't get any errors to show up. even with an image without an alt text, i got no errors.

**Comment by jbickar** [comment]
Compared to https://github.com/SU-SWS/acsf-cardinalsites/pull/134, I think this makes more sense in the profile.

I was able to get it to fix tables without headers and out-of-order header elements. I was not able to enter an `` tag without a `alt` attribute, the WYSIWYG stripped the entire tag.

**Comment by sherakama** [comment]
> Compared to [SU-SWS/acsf-cardinalsites#134](https://github.com/SU-SWS/acsf-cardinalsites/pull/134), I think this makes more sense in the profile.

It has to be everywhere.

**Comment by jbickar** [comment]
> It has to be everywhere.

[Reno, Chicago, Fargo, Minnesota](https://www.youtube.com/watch?v=ov4epAJRPMw)?

**Pull request merged**
